# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 14 Pro Max",
  "iPhone 14",
  "iPad Pro (12.9-inch) (6th generation)",
  "iPad Pro (11-inch) (4th generation)"
])

languages([
  "en-US",
  "ja"
])

# The name of the scheme which contains the UI Tests
scheme("Runner")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# For more information about all available options run
# fastlane action snapshot
